disabled_rules:
    - trailing_whitespace
    - type_name
    

opt_in_rules:
    - empty_count
    - empty_string

included:
    - Brastlewark

excluded:
    - 'Pods'

line_length:
    warning: 120
    error: 1000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 10
    error: 20

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 16
    error: 40

    
large_tuple:
    warning: 5
    error: 10
    
identifier_name:
    allowed_symbols: ["_","B"]
    max_length:
        warning: 60
        error: 60
    min_length:
        warning: 1

reporter: "xcode"

