# Uncomment the next line to define a global platform for your project
  platform :ios, '14.4'

target 'Gigimovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gigimovies
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 6.0'

  target 'GigimoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GigimoviesUITests' do
    # Pods for testing
  end

end